### ISSUE TITLE
Iced layershell crashes under Hyprland

### ISSUE THREAD

**Issue by BL-CZY** [waycrate/exwlshelleventloop#60]
Hi, I tried to run the counter example in the README.md file, and it panics right after.
Result of ```hyprctl verson```:
```
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)
```
Result of ```RUST_BACKTRACE=full cargo run```:
```
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_tiny_skia-0.13.0/src/window/compositor.rs:73:18:
Create clip mask
stack backtrace:
   0:     0x5baae2903875 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5baae2903875 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5baae2903875 - std::sys_common::backtrace::_print_fmt::h4feeb59774730d6b
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5baae2903875 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5baae29309eb - core::fmt::rt::Argument::fmt::h105051d8ea1ade1e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
   5:     0x5baae29309eb - core::fmt::write::hc6043626647b98ea
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
   6:     0x5baae28ff8cf - std::io::Write::write_fmt::h0d24b3e0473045db
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
   7:     0x5baae290364e - std::sys_common::backtrace::_print::h62df6fc36dcebfc8
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5baae290364e - std::sys_common::backtrace::print::h45eb8174d25a1e76
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5baae2904b99 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
  10:     0x5baae290493a - std::panicking::default_hook::hb5d3b27aa9f6dcda
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:298:9
  11:     0x5baae2905033 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:795:13
  12:     0x5baae2904f14 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
  13:     0x5baae2903d39 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5baae2904c47 - rust_begin_unwind
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
  15:     0x5baae11e5d23 - core::panicking::panic_fmt::ha02418e5cd774672
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  16:     0x5baae11e5ceb - core::panicking::panic_display::h5e2ae27b741fd199
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:262:5
  17:     0x5baae11e5ceb - core::option::expect_failed::h411c8586ddbfa53e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1995:5
  18:     0x5baae149ff62 - core::option::Option<T>::expect::hdc7e42bf6aeb89d7
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:898:21
  19:     0x5baae11fb5a4 - <iced_tiny_skia::window::compositor::Compositor as iced_graphics::compositor::Compositor>::create_surface::h3af2b2dd189decb1
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_tiny_skia-0.13.0/src/window/compositor.rs:72:24
  20:     0x5baae1271afc - <iced_renderer::fallback::Compositor<A,B> as iced_graphics::compositor::Compositor>::create_surface::h62d8c380c133ecf9
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_renderer-0.13.0/src/fallback.rs:288:17
  21:     0x5baae1257f5e - iced_layershell::application::run_instance::{{closure}}::hec25c88905075ee8
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_layershell-0.7.1/src/application.rs:339:9
  22:     0x5baae125bed5 - iced_layershell::application::run::{{closure}}::h28738e9dde62ddd7
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_layershell-0.7.1/src/application.rs:245:20
  23:     0x5baae1214451 - layershellev::WindowState<T>::running_with_proxy_option::h29ec705429b7c1eb
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/layershellev-0.7.1/src/lib.rs:1842:39
  24:     0x5baae121398e - layershellev::WindowState<T>::running_with_proxy::h51a6ec05bb0c3a10
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/layershellev-0.7.1/src/lib.rs:1804:9
  25:     0x5baae125b4cf - iced_layershell::application::run::h9ea1502f7b7341ff
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_layershell-0.7.1/src/application.rs:196:13
  26:     0x5baae126506e - iced_layershell::Application::run::h5977b971877b338d
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_layershell-0.7.1/src/lib.rs:184:9
  27:     0x5baae1292515 - iced_practice::main::ha78d06a78a47ac33
                               at ~/projects/iced_practice/src/main.rs:16:5
  28:     0x5baae1279e42 - core::ops::function::FnOnce::call_once::hd0be2b1e0e38091c
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  29:     0x5baae11ed595 - std::sys_common::backtrace::__rust_begin_short_backtrace::h267a433c5d9c8b15
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:155:18
  30:     0x5baae11ed606 - std::rt::lang_start::{{closure}}::h650ab01e467c0218
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:159:18
  31:     0x5baae28f877d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf57beef1b8c334ce
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:284:13
  32:     0x5baae28f877d - std::panicking::try::do_call::h65791b6ab5d9b39f
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  33:     0x5baae28f877d - std::panicking::try::h5a3dd25e8a379a23
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  34:     0x5baae28f877d - std::panic::catch_unwind::he2ce8403bab77de2
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  35:     0x5baae28f877d - std::rt::lang_start_internal::{{closure}}::h0b55d0da19178545
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:48
  36:     0x5baae28f877d - std::panicking::try::do_call::h33cbeb674c7644e0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  37:     0x5baae28f877d - std::panicking::try::h530c58b4c9daadba
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  38:     0x5baae28f877d - std::panic::catch_unwind::h92e02677901e11e4
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  39:     0x5baae28f877d - std::rt::lang_start_internal::hcee5ed89fc25829a
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:20
  40:     0x5baae11ed5da - std::rt::lang_start::hc60708e0175ccf60
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:158:17
  41:     0x5baae129443e - main
  42:     0x7e6bb7447e08 - <unknown>
  43:     0x7e6bb7447ecc - __libc_start_main
  44:     0x5baae11e68c5 - _start
  45:                0x0 - <unknown>
```

```Cargo.toml```:
[package]
name = "iced_practice"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
iced_layershell = "0.7.1"
```

System: 
```
OS: Arch Linux x86_64
Host: Dell G15 5510
Kernel: Linux 6.6.52-1-lts
```

GPU: Intel UHD Graphics @ 1.15 GHz [In]

Steps to reproduce:
1. copy the source of the counter example to main.rs
2. add cargo.toml
3. cargo run

**Comment by Decodetalkers** [comment]
Can you run any origin iced example?

**Comment by sundaram123krishnan** [comment]
In my system it works fine
```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)
```

**Comment by BL-CZY** [comment]
> Can you run any origin iced example? Seems it failed to create a composter.. iced use vulkan to draw surface..

It works fine with the original iced [counter](https://github.com/iced-rs/iced/blob/master/examples/counter/src/main.rs).
I have an iGPU from intel and a dGPU from Nvidia, and I only have Vulkan drivers installed for Nvidia

After installing the vulkan-intel package, the iced counter example stopped working, and the iced-layershell example is stuck in an infinite loop:
```
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@48:
```

**Comment by BL-CZY** [comment]
> In my system it works fine
> 
> ```shell
> Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
> Date: Sun Sep 8 16:48:21 2024
> Tag: v0.43.0, commits: 5196
> 
> flags: (if any)
> ```

What GPU's are you using?

**Comment by Decodetalkers** [comment]
I run on sway-git and meet the same probrem, but after I set the environment to 
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json
the problem gone

**Comment by BL-CZY** [comment]
> I run on sway-git and meet the same probrem, but after I set the environment to VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json the problem gone

I'll look into that, thank you!

**Comment by sundaram123krishnan** [comment]
Not sure how ur facing issue
my gpu related info:
```sh
-display
       description: VGA compatible controller
       product: TigerLake-LP GT2 [Iris Xe Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 03
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:166 memory:64000000-64ffffff memory:50000000-5fffffff ioport:3000(size=64) memory:c0000-dffff memory:41000000-47ffffff
       ```sh

**Comment by sundaram123krishnan** [comment]
```conf
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,1920x1080,auto,1,
```
my monitor configuration for hyprland
not sure if that helps

**Comment by BL-CZY** [comment]
> I run on sway-git and meet the same probrem, but after I set the environment to VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json the problem gone

This works, thank you so much!

**Comment by BL-CZY** [comment]
> Not sure how ur facing issue my gpu related info:
> 
> ```shell
> -display
>        description: VGA compatible controller
>        product: TigerLake-LP GT2 [Iris Xe Graphics]
>        vendor: Intel Corporation
>        physical id: 2
>        bus info: pci@0000:00:02.0
>        logical name: /dev/fb0
>        version: 03
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
>        configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
>        resources: irq:166 memory:64000000-64ffffff memory:50000000-5fffffff ioport:3000(size=64) memory:c0000-dffff memory:41000000-47ffffff
> ```

I suppose it's cuz of the lack of a Vulkan driver for my iGPU, and when I installed vulkan-intel, it couldn't choose between intel&nvidia. After specifying the env var it works
